### ISSUE TITLE
progress??

### ISSUE THREAD

**Issue by FriskTheFallenHuman** [kolessios/insource-legacy#1]
Sphanish:

Hola Quisiera Saber si habra una pronta actualizacion del projecto :D estoy ancioso de probar el codigo de los bots

English:

Hello I would like to know if there will be an early update of the project :D I am anxious to try the bots code

**Comment by kolessios** [comment]
Hello!

Thank you for your interest, I am now cleaning and documenting (in English) the Bots code so that it can be easily understood by any programmer.

The folder with everything you need to import the Bots in your project will be **coming soon** in this repository:

[https://github.com/WootsMX/SourceBots](https://github.com/WootsMX/SourceBots)

However, if you do not mind the spaghetti code, documentation in Spanish **and you just want to see a bit of the code**, you can see the files that contain the word **"bot", "schedule" or "component"** here:

[https://github.com/WootsMX/InSource/tree/master/game/server/in](https://github.com/WootsMX/InSource/tree/master/game/server/in)

**I do not recommend** you import the current code into your project, there are several parts of the code that were designed to work with the major changes to "InSource".

When I have the first clean and documented version of the project (probably in a few days) I will respond to this issue and place an entry in the reddit of [SourceEngine](https://www.reddit.com/r/SourceEngine/)

**Comment by kolessios** [comment]
The first public alpha version ready to test:
https://github.com/WootsMX/SourceBots

Please let me know your comments and suggestions :)
